### ISSUE TITLE
Version Number System

### ISSUE THREAD

**Issue by hoadlck** [TheYahya/sherlock#44]
I do not think that the version number system should use the date.  There are multiple systems out there, but they are all flavors of major.minor.maintenance. This allows the version number to have some meaning to other people.

https://github.com/sdushantha/sherlock/blob/e2c4dbf1ef69db80a9c6ebf591be874686e04301/sherlock.py#L20

**Comment by sdushantha** [comment]
I do understand your point, but what I was thinking of was that, since we are updating the code frequently, I don't think everyone is going to have the latest version on their computer. So, if use the year.month.day format, users will get and idea if their version has been out dated or not. 

If major.minor.maintenance is the standard and has a more meaning to other people, I'm more than  happy to change it. 😊

**Comment by sdushantha** [comment]
@hoadlck Can you delete your fork of this repo?
I want to transfer the ownership of this repo to you. To do that, you first have to delete your fork.

**Comment by hoadlck** [comment]
@sdushantha  Uh... you are the owner of this repo. You cannot abandon your child! :)

I am on break now, so I had some free time to contribute. But, on 2019-01-02, the daily grind starts up again, and I am unsure how much time I will have to dedicate to this.

**Comment by jcs090218** [comment]
Wait, this are not the end of the conversation, right? I can still see https://github.com/TheYahya/sherlock/blob/508eb88724dbe20dedf07dc00527ad4f32c93a77/sherlock.py#L24 at the moment, yet the latest commit is already on `2019.01.03`. Maybe just have something that are regularly used like `0.0.1`, etc.
