### ISSUE TITLE
issues with hearthis.at

### ISSUE THREAD

**Issue by Czechball** [TheYahya/sherlock#66]
I don't know how to add a user lookup on https://hearthis.at/.
The user placeholder is hearthis.at/[user] , but when incorrect user is entered, it will just search the string.
Now, I've tried "errorType": "message" with the message "Search results", but I was getting false positives. I also tried "errorType": "response_url" with the URL https://hearthis.at/search/?q= and "regexCheck": "^[a-zA-Z][a-zA-Z0-9_-]*$", but still false positives. Does anyone have an idea how to solve this?

**Comment by hoadlck** [comment]
I see that they have an API (https://hearthis.at/api-v2/).  But, there does not seem to be a way to query if a user exists.

It looks like the "errorUrl" field in the JSON would have to be extended so that the user name could show up.  Then you could have the "errorUrl" value be "https://hearthis.at/search/?q={}/". But, many other errorURLs do not have the user name included, so the approach would have to be backwards compatible.

**Comment by Czechball** [comment]
I see. But I don't understand why the first approach didn't work, because the unique string "Search result" was clearly displayed in every failed user lookup attempt.

**Comment by 0Erik-H** [comment]
I think I might have found a solution. It seems that (if there isn't a user found) hearthis.at responds with a 404 error status code with only some JavaScript in the body to redirect to the search page. Sherlock stops at this first stage, which would explain why trying to find "Search results" doesn't work. Detecting the error URL also doesn't work as it responds with the request URL (before redirecting through JavaScript). The error code provided, however, means that adding hearthis.at is easy now that we know it responds with one. Just use: `"errorType": "status_code"`.

**Comment by Czechball** [comment]
Looks like it's working, thanks for the help. I'll include hearthis.at in my next PR.

**Comment by ristiluomasami-stack** [comment]
Compleate it
